apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64-encoded 'password'
  MYSQL_DATABASE: c3RvY2tz          # Base64-encoded 'stocks'
  MYSQL_USER: cm9vdA==             # Base64-encoded 'root'
  MYSQL_PASSWORD: cGFzc3dvcmQ=      # Base64-encoded 'password'
